version: '3.0'
services:
  mongodb:
    image: "mongo"
    volumes:
      - data:/data/db
    env_file:
      - ./env/mongo.env
    ports:
       - 27017:27017
  backend:
    build: ./backend
    ports:
      - 3000:3000
    volumes:
      - ./backend:/aplicacion
      - /app/node_modules
    env_file:
      - ./env/backend.env
    depends_on:
      - mongodb
  frontend:
    build: ./frontend
    ports:
      - 80:80
    volumes:
      - ./frontend/src:/aplicacion/src
    depends_on:
      - backend
volumes:
  data:
